name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx (Docker Build Cloud)
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "elitedevltd/worehouse"

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          tags: "${{ vars.DOCKER_USER }}/warehouse-backend:latest"
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          tags: "${{ vars.DOCKER_USER }}/warehouse-frontend:latest"
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
